### ISSUE TITLE
Allow querying backlight power status

### ISSUE THREAD

**Issue by pimterry** [pimterry/rpi-backlight#1]

**Comment by steven-work-space** [comment]
Hey ! I have worked on it :)

#4

**Comment by ricekrispies** [comment]
I may be misunderstanding what the query returns, but here is my issue - on a normal/successful boot into Raspbian (Pi boots into the gui, display is on), _--power_ will return _True_, but when I pull the power on just the display (unplug it), _--power_ still returns _True_.

My intent is to run a script that repeatedly queries _rpi-backlight --power_, and if it returns anything other than _True_, it will shut down the Pi.  Is it possible I am doing something wrong?

**Comment by pimterry** [comment]
Ah, I think there's some confusion here @ricekrispies - this API tells you if the pi is attempting to provide power, not if a screen is successfully attached.

That means if you turn the screen off in software, it will report that the power is off, but disconnecting the hardware directly won't have any effect. This library is a wrapper around the backlight drivers themselves, and just reports the info they provide, so we can't directly change this here. I'm not sure if there is a mechanism to detect if the screen is currently connected, but I'm afraid you'll need to investigate that upstream.

**Comment by pimterry** [comment]
I'm going to close this ticket actually, since it was fixed from our pov in the attached PR, and any other changes like that will need to happen elsewhere.
