### ISSUE TITLE
Simply attempting to require library on unsupported hardware shouldn't throw exception

### ISSUE THREAD

**Issue by darrylhodgins** [pimterry/rpi-backlight#6]
For convenience and for a better IDE, I do my development work on a non-pi machine.

Simply calling `var backlight = require("rpi-backlight");` causes an exception on unsupported hardware, leaving no elegant way to handle the case of unsupported hardware.

Ideally, I should be able to import the library without complaint, and handle the exception in the code that calls the backlight on/off methods.

```
Error: Backlight control not supported (/sys/class/backlight/rpi_backlight does not exist)
    at Object.<anonymous> (/PATH/TO/PROJECT/node_modules/rpi-backlight/index.js:27:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/PATH/TO/PROJECT/dist/index.js:4:17)
    at Module._compile (module.js:570:32)
```

**Comment by pimterry** [comment]
You can handle it fairly elegantly with

```
try {
  var backlight = require("rpi-backlight");
} catch (e) {
  // ... Do something
}
```

Personally I prefer that style, and later being able to check just `if (backlight)`, rather than having to remember to catch around every single method call. Is there a reason that doesn't work for you?

**Comment by darrylhodgins** [comment]
I had considered that, but I find it kind of gross.  But I will admit, [this solution](https://github.com/darrylhodgins/rpi-backlight/commit/b1da3b96e4dbcac111296bb54b48eb24008f29c1#diff-168726dbe96b3ce427e7fedce31bb0bc) isn't any better ;)

**Comment by darrylhodgins** [comment]
I don't mind closing this one.  I can abstract the try..catch block in a separate file so I don't need to look at it 😉

**Comment by pimterry** [comment]
Haha, fair enough. I think this is the simplest easy api for this, but if you do get a better idea later, let me know.
