### ISSUE TITLE
Allow including the module on not-supported devices

### ISSUE THREAD

**Issue by Roemer** [pimterry/rpi-backlight#7]
There might be cases where you are temporarily developing an application that uses rpi-backlight on a device without backlight. Right now, you cannot run it as rpi-backlight immediately throws.

How about just throwing the exception when a function is used instead of on load time?
Additionaly, an exposed method called `isSupported` could make sense to check if the current device supports backlight or not.

**Comment by pimterry** [comment]
Fixed in v0.4.0
